### ISSUE TITLE
Brother, can you help me get a music player

### ISSUE THREAD

**Issue by ytmsuhsff** [yohans-t/Adey-Coder#1]
Brother, can you help me get a music player

**Comment by ytmsuhsff** [comment]
Hello, I installed wavesurfer JS audio wave display, but the wave loading speed is very slow. You need to save the wave to the database to load the wave quickly. Is it possible to solve this problem.
(wavesurfer.js     https://wavesurfer-js.org/  )

Just like them
https://icons8.com/music/search/beach
https://tunetank.com/tracks/

This is my website
http://www.partymusic.cn/

我的邮件 304955091@qq.com

**Comment by yohanstesfaye** [comment]
@ytmsuhsff the wavesurfer-js load by analyzing a waveform on the user machine so it can't be saved to a database and the speed of loading a wave visualization depends on the file size of the audio file that is to be analyzed.
